name: "EpiAction"
description: "An action for Epitech"
author: "Antoine BERGER"
labels: ["epitech"]
branding:
  icon: "mic"
  color: "blue"
inputs:
  name:
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "composite"
  jobs:
    hello:
      steps:
        - run: echo "Hello ${{ inputs.name }}!"
        - run: echo "::set-output name=time::$(date)"
          id: step1
        - run: echo "::set-output name=who::$(whoami)"
          id: step2
      outputs:
        time: ${{ steps.step1.outputs.time }}
        who: ${{ steps.step2.outputs.time }}
