name: "EpiAction"
description: "An action for Epitech"
author: "Antoine BERGER"
branding:
  icon: "mic"
  color: "blue"
inputs:
  binary:
    description: "The name of the binary file"
    required: true
    default: "a.out"
runs:
  using: "composite"
  steps:
    # try to execute the makefile
    - name: "Create binary file"
      id: make
      run: make
      shell: bash
    - name: "Clean object files"
      if: steps.make.outcome == 'failure'
      run: make clean
      shell: bash
    # try to run the program
    - name: "Run program"
      run: ./$(inputs.binary)
      shell: bash
    # try to run the make tests_run
    - name: "Run unit tests"
      if: always()
      run: make tests_run
      shell: bash
    # try to run the coverage
    - name: "Run coverage"
      if: always()
      run: make coverage
      shell: bash
    # return if it fails or not
    - name: "Return status"
      if: always()
      run: |
        if [ -f "tests/units.xml" ]; then
          echo "##[set-output name=tests;]$(cat tests/units.xml)"
        fi
        if [ -f "tests/coverage.xml" ]; then
          echo "##[set-output name=coverage;]$(cat tests/coverage.xml)"
        fi
      shell: bash
      id: return
