name: "EpiAction"
description: "An action for Epitech"
author: "Antoine BERGER"
labels: ["epitech"]
branding:
  icon: "mic"
  color: "blue"
inputs:
  name:
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "composite"
  steps:
    - name: "Hello"
      run: echo "Hello ${{ inputs.name }}!"
      shell: bash
    - name: "Goodbye"
      run: echo "Goodbye ${{ inputs.name }}!"
      shell: bash
