name: "Test action workflow"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          name: "Antoine"
      - name: "Check output"
        run: |
          echo "Hello Antoine!" >> expected.txt
          echo "Goodbye Antoine!" >> expected.txt
          diff expected.txt output.txt
          rm expected.txt output.txt